"""orcamento tipo venda equipamento

Revision ID: 073c6f94c21f
Revises: 39dea82fd3a5
Create Date: 2026-08-10 19:09:33.641699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073c6f94c21f'
down_revision = '39dea82fd3a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_venda_equipamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('ncm', sa.String(length=20), nullable=True),
    sa.Column('partnumber', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=True),
    sa.Column('garantia_meses', sa.Integer(), nullable=True),
    sa.Column('prazo_entrega', sa.String(length=100), nullable=True),
    sa.Column('ipi_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('icms_percentual', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_venda_equipamento_id'), 'itens_venda_equipamento', ['id'], unique=False)
    op.add_column('orcamentos', sa.Column('tipo', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamentos', 'tipo')
    op.drop_index(op.f('ix_itens_venda_equipamento_id'), table_name='itens_venda_equipamento')
    op.drop_table('itens_venda_equipamento')
    # ### end Alembic commands ###
