"""os equipamentos n para n

Revision ID: 39dea82fd3a5
Revises: f76c7dbb714d
Create Date: 2026-08-10 14:48:17.169938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dea82fd3a5'
down_revision = 'f76c7dbb714d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordem_servico_equipamento',
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('ordem_servico_id', 'equipamento_id')
    )
    op.drop_constraint('ordens_servico_equipamento_id_fkey', 'ordens_servico', type_='foreignkey')
    op.drop_column('ordens_servico', 'equipamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_servico', sa.Column('equipamento_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ordens_servico_equipamento_id_fkey', 'ordens_servico', 'equipamentos', ['equipamento_id'], ['id'])
    op.drop_table('ordem_servico_equipamento')
    # ### end Alembic commands ###
