"""financeiro detalhado - despesas, contas a receber

Revision ID: 4fec35d5bfff
Revises: 073c6f94c21f
Create Date: 2026-08-12 17:31:50.041627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fec35d5bfff'
down_revision = '073c6f94c21f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_despesas_id'), 'despesas', ['id'], unique=False)
    op.add_column('orcamentos', sa.Column('pago', sa.Boolean(), nullable=True))
    op.add_column('orcamentos', sa.Column('data_pagamento', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orcamentos', 'data_pagamento')
    op.drop_column('orcamentos', 'pago')
    op.drop_index(op.f('ix_despesas_id'), table_name='despesas')
    op.drop_table('despesas')
    # ### end Alembic commands ###
