"""add partnumber peca

Revision ID: 6f3890570dc6
Revises: 8a9387fc9e51
Create Date: 2026-08-10 13:20:22.420858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3890570dc6'
down_revision = '8a9387fc9e51'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pecas', sa.Column('partnumber', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pecas', 'partnumber')
    # ### end Alembic commands ###
