"""add itens servico os

Revision ID: 9836394d02df
Revises: 6f3890570dc6
Create Date: 2026-08-10 13:44:44.350615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9836394d02df'
down_revision = '6f3890570dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens_servico_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_servico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=250), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_servico_os_id'), 'itens_servico_os', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itens_servico_os_id'), table_name='itens_servico_os')
    op.drop_table('itens_servico_os')
    # ### end Alembic commands ###
