"""add marca modelo peca

Revision ID: e29312ceb36f
Revises: 9836394d02df
Create Date: 2026-08-10 14:02:27.159252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29312ceb36f'
down_revision = '9836394d02df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pecas', sa.Column('marca', sa.String(length=100), nullable=True))
    op.add_column('pecas', sa.Column('modelo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pecas', 'modelo')
    op.drop_column('pecas', 'marca')
    # ### end Alembic commands ###
