"""custo unitario venda equipamento

Revision ID: ef73df3bf545
Revises: 4fec35d5bfff
Create Date: 2026-08-12 18:52:01.333684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef73df3bf545'
down_revision = '4fec35d5bfff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itens_venda_equipamento', sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_venda_equipamento', 'custo_unitario')
    # ### end Alembic commands ###
