"""add numero

Revision ID: f76c7dbb714d
Revises: e29312ceb36f
Create Date: 2026-08-10 14:15:47.857235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76c7dbb714d'
down_revision = 'e29312ceb36f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordens_servico', sa.Column('numero', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordens_servico', 'numero')
    # ### end Alembic commands ###
